# Site settings
title: Holmes Law Office - Cedar Rapids, Iowa
email: jamesc@holmesatty.com
description: > #
  The Holmes Law Office is General Practice located in Cedar Rapids, Iowa. We
  specialize in business, commercial, and criminal law, contracts, debtor and
  creditor litigation, real estate, taxation and tax returns, wills, trusts,
  estate planning and probate law.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://holmesatty.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
